### ISSUE TITLE
TotW Frequency 

### ISSUE THREAD

**Issue by atkawa7** [abseil/abseil.github.io#57]
How frequent are the  TotW going to be posted? When I watched Titus talk. I think he said they are more than 120. If its one per week then 2 years ???

**Comment by manshreck** [comment]
More frequent than that. We'll be releasing them as we convert/review them, and we may be releasing them out of order based on their applicability/usefulness. Some will not be released because they are either internal or have been obviated by language/tools updates, etc.. I expect we'll start releasing some as early as next week, and will set up both the tips and blog with RSS feeds by then, so you can get notified of new tips.
