### ISSUE TITLE
operator<< for StrAppend

### ISSUE THREAD

**Issue by OlafvdSpek** [abseil/abseil.github.io#68]
Abseil looks very interesting!

I've been using StrAppend-like and StrCat-like functions for some time now and they work great.
I use operator<< for StrAppend though, which looks very natural. Could Abseil consider supporting this?

**Comment by tituswinters** [comment]
operator<< is, unfortunately, a design problem.

StrCat (and StrAppend) are 5-10x faster than the operator<< approach specifically because there is a single overall function call (the call to StrCat).  That means that we can figure out the precise size of the resulting std::string return value in a single allocation/reservation, and do a single copy of all of the string data (and a single conversion+copy for the numeric data).  

Doing this as a chain of calls (as is necessary in the operator<< approach) is, at this point, infeasible for performance reasons.  

On top of that, our compiler folks have specifically asked us not to perpetuate use of that paradigm. Every call to operator<< style APIs has outsized effect on compilation time because of the amount of lookup / resolution that has to be done.  

In short: definitely no.
